name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build default scheme using xcodebuild command
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build
        working-directory: ./safari
        run: |
          xcodebuild build -configuration Release
      - name: Prepare artifact
        run: |
          mkdir safari/out
          mv safari/build/Release/bskyUnGeoBlock.app safari/out/
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: bskyUnGeoBlock-safari
          path: ./safari/out/
          include-hidden-files: true
